CREATE TABLE CW2.TrailUser(
    UserID INT NOT NULL IDENTITY,
    EmailAddress VARCHAR (320) NOT NULL,
    RoleType VARCHAR (5) NOT NULL

    CONSTRAINT PK_User PRIMARY KEY (UserID),
    CONSTRAINT UQ_UserEmail UNIQUE (EmailAddress)
)
